In [1]:
 import numpy as np

In [2]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
 list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
 np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
 np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
#### linearly spaced(linspace)###

In [13]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [14]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
import numpy as np

In [17]:
np.random.rand(3,2)

array([[0.46899694, 0.60614565],
       [0.46950365, 0.28195219],
       [0.83332744, 0.62849179]])

In [18]:
np.random.randn(3,2)

array([[-0.45813864,  0.83079092],
       [-1.17627348,  1.14504038],
       [ 0.2329978 ,  0.57248888]])

In [19]:
np.random.randint(34,100)

57

In [20]:
np.random.randint(20,56,100)

array([33, 31, 55, 29, 26, 41, 43, 45, 39, 34, 25, 39, 52, 29, 36, 48, 35,
       49, 31, 54, 45, 36, 40, 27, 23, 21, 51, 22, 47, 48, 34, 37, 44, 34,
       39, 36, 50, 40, 35, 41, 47, 29, 47, 37, 28, 27, 34, 45, 43, 28, 31,
       21, 30, 37, 43, 33, 47, 42, 37, 42, 20, 50, 49, 34, 55, 40, 53, 48,
       51, 32, 55, 54, 49, 41, 21, 20, 33, 40, 33, 44, 48, 53, 52, 48, 45,
       26, 48, 23, 49, 30, 25, 53, 21, 44, 37, 35, 43, 49, 29, 39])

In [21]:
sample_array=np.arange(30)

In [22]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
rand_array=np.random.randint(0,100,20)

In [24]:
rand_array

array([78, 95, 52, 66, 11,  9, 48, 55, 94, 17, 46, 97, 38, 86, 29, 87, 62,
       78, 97, 78])

In [25]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
sample_array.reshape(3,7)

ValueError: ignored

In [27]:
rand_array.min()

9

In [28]:
rand_array.max()

97

In [29]:
sample_array.dtype

dtype('int64')

In [30]:
sample_array [3:7]

array([3, 4, 5, 6])

In [31]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
sample_array[1:4]=100

In [33]:
sampe_array

NameError: ignored

In [34]:
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [35]:
####### TWO DIMENSIONAL ARRAY#####

In [36]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix


array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [37]:
sample_matrix[0][2]

1

In [38]:
sample_matrix[1][2]

21

In [39]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [40]:
sample_matrix[2]

array([56, 76, 24,  7])

In [41]:
###### SELECTION TECHNIQUES#####

In [42]:
import numpy as np


In [43]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [45]:
np.exp(sample_array) ##exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [46]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [47]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [48]:
np.max(sample_array)

19

In [49]:
np.min(sample_array)

1

In [50]:
np.argmax(sample_array)

18

In [51]:
np.argmin(sample_array)

0

In [52]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [53]:
np.std(sample_array)

5.477225575051661

In [54]:
np.var(sample_array)

30.0

In [55]:
np.mean(sample_array)

10.0

In [56]:
array=np.random.randn(3,4)
array

array([[ 0.26359835,  2.59972939,  0.53987982, -0.88962563],
       [ 0.58545097,  1.52439349,  1.56796902, -1.00744933],
       [ 0.2863858 ,  1.03380147,  0.12953824,  0.18234991]])

In [57]:
np.round(array,decimals=4)

array([[ 0.2636,  2.5997,  0.5399, -0.8896],
       [ 0.5855,  1.5244,  1.568 , -1.0074],
       [ 0.2864,  1.0338,  0.1295,  0.1823]])

In [58]:
np.round(array,decimals=1)

array([[ 0.3,  2.6,  0.5, -0.9],
       [ 0.6,  1.5,  1.6, -1. ],
       [ 0.3,  1. ,  0.1,  0.2]])

In [59]:
sports=np.array(['golf','cricket','fball','cricket','football'])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')

In [60]:
###pandas->To create data,create data,create table,manipulation